version: "3.9"

services:
  web:
    container_name: movie_django
    build:
      context: .
      dockerfile: python.Dockerfile
    restart: always
    ports:
      - '8000:8000'
    env_file:
      - .env.example
    command: /python-entrypoint.sh
    volumes:
      - ./static:/app/static
      - ./media:/app/media

volumes:
  media:
  static:
