version: "3.9"

services:
  web:
    container_name: django
    build:
      context: .
      dockerfile: python.Dockerfile
    restart: always
    expose:
      - 8000
    env_file:
      - .env.prod
    command: /python-entrypoint.sh
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - nginx

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    restart: always
    ports:
      - '80:80'
    volumes:
      - static:/app/static
      - media:/app/media

volumes:
  media:
  static:
